language: haskell

ghc:
    - "7.6"

before_script:
    - uname -a
    - echo "hello before script!"

script: 
    - cabal install -j

after_success:
    - echo "after success" 
    - ./scrum-linter
    - hlint .

